name: Build and Upload Release Assets

on:
  push:
    tags:
      - "*-*-*"
permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Upload JAR Files to Release
        uses: softprops/action-gh-release@v2
        with:
          files: fabric/build/libs/*.jar
